### ISSUE TITLE
7 Days Savalation (CN)

### ISSUE THREAD

**Issue by pent0** [EKA2L1/Compatibility-List#137]
# App summary
- App name: 7 Days Savalation (CN)
- Platform: Symbian 60 3rd

# EKA2L1 info
- Build name: master
- Buid hash: c0ed8ebe

# Test environment summary
- Tested by: Ink321
- OS: Windows 10
- CPU: ?
- GPU: ?
- RAM: ? GB

# Issues
Game requires SMS activation. Freeze on using it.

# Screenshots
None

# Log
[EKA2L1_Sava.log](https://github.com/EKA2L1/Compatibility-List/files/5201905/EKA2L1_Sava.log)

# Recommended labels
- Softlock
- Menu

**Comment by TRR95** [comment]
Moved over here: https://github.com/EKA2L1/Compatibility-List/issues/23
