### ISSUE TITLE
Old Submission

### ISSUE THREAD

**Issue by FrenesiGG** [EKA2L1/Compatibility-List#222]
# App summary
- App name: Habbo Islands
- Platform: N-Gage

# EKA2L1 info
Build: EKA2L1 v0.0.1 (HEAD-f4adb46d (2020-dic-11)
Device: N-Gage QD G 04.10 Game Developer SW Variant Symbian OS 6.1/s60v1 (rh-29) 

# Test environment summary
- OS: Windows 10 Home 64-bit
- CPU: i5-6400
- GPU: NVIDIA GTX 1060 GB
- RAM: 16 GB

# Issues
Boot but only can be seen a white screen.

# Log
[EKA2L1.log](https://github.com/EKA2L1/Compatibility-List/files/5682764/EKA2L1.log)
Examples of code: 
W { eka2l1::oom_ui_app_session::fetch: Unimplemented opcode for OOM AKNCAP server: 0x3F, fake return with epoc::error_none }
E { eka2l1::hle::lib_manager::call_svc: Unimplement system call: 0x800056! }
T { eka2l1::kernel::thread::kill: Thread Habbo Islands panicked with category: USER and exit code: 21 (Accessing element of 8-bit descriptor out of range) }
T { eka2l1::kernel::thread::kill: Thread MediaServerTaskThread forcefully killed with category: None and exit code: 0  }

**Comment by yfaizin1** [comment]
cannot open ngage intallers v2 in rom e6, 5230, n95?

Pada tanggal Min, 13 Des 2020 2.50 AM, ccjkz11 <notifications@github.com>
menulis:
