### ISSUE TITLE
Asphalt 3: Street Rules (NG 2.0 Version)

### ISSUE THREAD

**Issue by TRR95** [EKA2L1/Compatibility-List#278]
# App summary
- App name: Asphalt 3: Street Rules
- Platform: ?

# EKA2L1 info
- Build name: 
- Buid hash

# Test environment summary
- Tested by: ?
- OS: ?
- CPU: AMD/Intel?
- GPU: AMD/NVIDIA/Intel?
- RAM: ? GB

# Issues
The game is broken because EKA2L1 doesn't supported N-Gage 2.0 games yet

# Screenshots

# Log

# Recommended labels
- A?
- B?
- C?

**Comment by fazidroid** [comment]
Pls I really need to play Asphalt 3 ngage 2.0 version
