### ISSUE TITLE
How to play Games on N-Gage 2.0 s60v5

### ISSUE THREAD

**Issue by yfaizin1** [EKA2L1/Compatibility-List#294]
How to play Games on N-Gage 2.0 s60v5 on ROMs 5800, install loucher is done 😥
https://youtu.be/EJ1C_86Jg3M![NOTABLE-00941.jpg](https://user-images.githubusercontent.com/73581900/131204901-5dcfd525-92df-467a-874a-35ee8e224405.jpg)

**Comment by pent0** [comment]
Not support at the moment, sorry.
