### ISSUE TITLE
The Elder Scrolls Travels: Shadowkey

### ISSUE THREAD

**Issue by xTMODx** [EKA2L1/Compatibility-List#295]
# App summary
- App name: The Elder Scrolls Travels: Shadowkey
- Platform: N-Gage

# EKA2L1 info
- Build name: EKA2L1 0.0.6

# Test environment summary
- Tested by: ?
- OS: Android 10
- CPU: Qualcomm SD865+
- GPU: Adreno 650
- RAM: 12GB
- Device Modal: Samsung Galaxy Note 20 Ultra 5G (SM-N9860)

# Issues
Sound issues

# Video
https://youtu.be/5j2hVXg06I8

# Log

# Recommended labels
- Status: Playable
- Sound Issues

**Comment by pent0** [comment]
Move to #127 please, thanks!
