### ISSUE TITLE
Not support on O.S MocorDroid 4.4.4/Android Kitkat

### ISSUE THREAD

**Issue by yfaizin1** [EKA2L1/Compatibility-List#297]
Can you support Andromax Prime v5.7 phone maybe. O.S MocorDroid 4.4.4/Android Kitkat/Custom Rom Android 6.2, 32 bit, Processor: dual-core Speadtrum A7 1,2GHz, Memori RAM : 512Mb Pleas!

**Comment by yfaizin1** [comment]
Pleas

**Comment by kenobizero** [comment]
I think with specification like that will run very slowly like 2-4 fps (^w^)

**Comment by yfaizin1** [comment]
Do you have link download apk support to this phone? Eka2l1 32bit

Pada tanggal Kam, 3 Mar 2022 10.43 AM, kenobizero ***@***.***>
menulis:

**Comment by kenobizero** [comment]
EKA2L1 now support on 32 bit android but to play decent gameplay you have to specs 
Minimum :
Android 5.0
Snapdragon 425 or high
Quadcore 1.4 ghz
Ram 2gb
Tested on Asus Live L1

**Comment by yfaizin1** [comment]
Thanks for the tip! Maybe next time i hope support😁 same emulator j2me
loader

Pada tanggal Min, 13 Mar 2022 7.50 AM, kenobizero ***@***.***>
menulis:

**Comment by pent0** [comment]
There's no plan to lower down the requirement more, I must close this!

**Comment by yfaizin1** [comment]
Ok, thanks.

Pada tanggal Min, 13 Mar 2022 5.37 PM, pent0 ***@***.***>
menulis:
